# Site settings
baseurl = "https://stevesloan.github.io"
languageCode = "en-us"


theme = "hugo-litecoin-theme"
googleAnalytics = ""
ignoreFiles = [ "\\.scss$", "\\.sass$" ]

# Link custom assets relative to /static
custom_css = []
custom_js  = []

# Possibility to disable external/additional fonts
# Exception: Fontawesome
disableFonts = false

[Taxonomies]
tag = "tags"

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[params]
description = "Litecoin is a cryptocurrency that enables instant payments to anyone in the world and that can be efficiently mined with consumer-grade hardware."

  [params.downloadCommon]
    releaseNotesURL = "http://blog.litecoin.org/2015/12/litecoin-core-v01040.html"
    upgradeNotesURL = "https://litecoin.info/Upgrading_Litecoin"

  [params.footerCommon]
    [[params.footerCommon.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/LitecoinProject"

    [[params.footerCommon.social]]
      icon = "fa-comments"
      link = "https://web.telegram.org/#/im?p=@Litecoin"

    [[params.footerCommon.social]]
      icon = "fa-reddit-alien"
      link = "https://www.reddit.com/r/litecoin/"




[Languages]
  [Languages.en]
    lang = "English"
    title = "Litecoin - Open source P2P digital currency"
    weight = 1

  # Hero section
  [Languages.en.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Global Decentralized Currency"
    subtitle = "Based on Blockchain Technology"
    button_text = "Download"

  # Navigation
  [Languages.en.navigation]
    brand = "litecoin"
    download = "Download"
    about = "About"
    team = "Team"
    contact = "Contact"

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10


  # About section
  [Languages.en.about]
    enable = true
    title = "What is Litecoin?"
    subtitle = "Litecoin is a peer-to-peer Internet currency that enables instant, near-zero cost payments to anyone in the world. Litecoin is an open source, global payment network that is fully decentralized without any central authorities. Mathematics secures the network and empowers individuals to control their own finances. Litecoin features faster transaction confirmation times and improved storage efficiency than the leading math-based currency. With substantial industry support, trade volume and liquidity, Litecoin is a proven medium of commerce complementary to Bitcoin."

    [[Languages.en.about.row]]

      [[Languages.en.about.row.list]]
        icon = "fa-group"
        title = "Community"
        description =  '<p class="text-no-margin text-left text-muted">Find support across a growing number of Litecoin communities:</p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">Litecoin Forums</a></li> <li><a href="http://www.reddit.com/r/litecoin">Reddit Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Search for Users on Twitter</a></li> <li><a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> network channels <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (for general users) and <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (for developers).</li> </ul>'

      [[Languages.en.about.row.list]]
        icon = "fa-laptop"
        title = "Resources"
        description = 'Find general information as well as a list of services and exchanges that support Litecoin at the <a href="http://litecoin.info">Litecoin Wiki</a>. <br> Up-to-date network statistics can be found at <a href="http://ltc.block-explorer.com/charts">Litecoin Block Explorer Charts</a>. <br> Source code for Litecoin Core and related projects are available on <a href="https://github.com/litecoin-project">GitHub</a>.'

      [[Languages.en.about.row.list]]
        icon = "fa-heart"
        title = "Open Source Software"
        description = "Litecoin is an open source software project released under the MIT/X11 license which gives you the power to run, modify, and copy the software and to distribute, at your option, modified copies of the software. The software is released in a transparent process that allows for independent verification of binaries and their corresponding source code."
[[Languages.en.about.row]]
      [[Languages.en.about.row.list]]
        icon = "fa-link"
        title = "Blockchain"
        description = "The Litecoin blockchain is capable of handling higher transaction volume than its counterpart - Bitcoin. Due to more frequent block generation, the network supports more transactions without a need to modify the software in the future. <br />As a result, merchants get faster confirmation times, while still having ability to wait for more confirmations when selling bigger ticket items."

      [[Languages.en.about.row.list]]
        icon = "fa-lock"
        title = "Wallet Encryption"
        description = "Wallet encryption allows you to secure your wallet, so that you can view transactions and your account balance, but are required to enter your password before spending litecoins. <br />This provides protection from wallet-stealing viruses and trojans as well as a sanity check before sending payments."

      [[Languages.en.about.row.list]]
        icon = "fa-money"
        title = "Mining Reward"
        description = "Miners are currently awarded with 25 new litecoins per block, an amount which gets halved roughly every 4 years (every 840,000 blocks). <br />The Litecoin network is therefore scheduled to produce 84 million litecoins, which is 4 times as many currency units as Bitcoin."

  # download section
  [Languages.en.download]
    enable = true
    title = "Download"
    subtitle = "<a href='http://blog.litecoin.org/2015/12/litecoin-core-v01040.html'>Release Notes</a> | <a href='https://litecoin.info/Upgrading_Litecoin'>Upgrade Notes</a>"
    gpg = "GPG Signatures"
    download = "Download"
    source = "Source"
    walletfor = "Wallet for"
    releaseNotes = "Release Notes"
    upgradeNotes = "Upgrade Notes"


  # Contact section
  [Languages.en.contact]
    enable = true
    title = "Contact us"
    subtitle  = "You can contact Litecoin project development team at <a href='mailto:contact@litecoin.org'>contact@litecoin.org</a>"


  # Footer section
  [Languages.en.footer]
    enable = true
    copyright = "Copyright &copy; 2011-2016 Litecoin Project. <br />All rights reserved."

    [[Languages.en.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[Languages.en.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"



# FRENCH _____________________________

[Languages.fr]
  lang = "Francais"
  weight = 2

  title = "Litecoin - Monnaie électronique décentralisée et open source"

[Languages.fr.hero]
  # To change the background image of the hero, replace 'header-bg.jpg' in
  # the 'static/img' folder.
  title = "fr-Global Decentralized Currency"
  subtitle = "frBased on Blockchain Technology"
  button_text = "fDownload"

[Languages.fr.Taxonomies]
plaque = "plaques"

[Languages.fr.navigation]
brand = "litecoin"
about = "About"

[Languages.fr.about]
title = "Litecoin, c'est quoi ?"
subtitle = "Litecoin est une devise Internet peer-to-peer, qui permet des paiements instantanés, avec des coûts proches de zéro à quiconque dans le monde. Litecoin est un réseau de paiement mondial open source, qui est entièrement décentralisé sans autorités centrale. Les utilisateurs peuvent mainteant contrôler leurs propres finances, securisées par un systeme basé entierement sur des mathématiques. Par rapport à Bitcoin, les transactions Litecoin sans plus rapides à confirmer et ont une efficacité de stockage accrue. De part son utilisation par l'industrie, le volume d'échange et de liquidité sur les marchés d'échange, Litecoin est un moyen de commerce complémentaire à Bitcoin, qui a fait ses preuves."

[[Languages.fr.about.row]]

[[Languages.fr.about.row.list]]
  icon = "fa-shopping-cart"
  title = "Community"
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

[[Languages.fr.about.row.list]]
  icon = "fa-laptop"
  title = "Resources"
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

[[Languages.fr.about.row.list]]
  icon = "fa-lock"
  title = "Wallet Encryption"
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

# SPANISH _____________________________

[Languages.sp]
  lang = "Spanish"
  weight = 2

  title = "Litecoin - sp"


# CHINESE _____________________________

[Languages.cn]
lang = "中文"
title = "莱特币 - 开源的P2P数字货币"
  weight = 1

# Hero section
[Languages.cn.hero]
  # title = "Global Decentralized Currency"
  # subtitle = "Based on Blockchain Technology"
  button_text = "下载"

# Navigation
[Languages.cn.navigation]
  brand = "litecoin"
  download = "下载"
  about = "About"
  team = "Team"
  contact = "Contact"

  # prepended links
  #[[menu.prepend]]
  #  url = "http://gohugo.io"
  #  name = "Hugo"
  #  weight = 10

  # postpended links
  [[menu.postpend]]
    url = "https://litecointalk.io/"
    name = "Forum"
    weight = 10


# About section
[Languages.cn.about]
  enable = true
  title = "什么是莱特币？"
  subtitle = "莱特币加密货币是一款点对点的分布式网络货币系统。她可以在瞬间，以低廉交易费的方式向全世界的任意角落付款。莱特币是一个开源的项目，全球性的支付网络，她没有任何的中央控制节点。严谨的密码学协议使这个网络系统充分保障每一位用户的财务安全。莱特币相对比特币的加密货币系统，拥有更快的交易确认时间，更高的网络交易容量和效率。莱特币现在拥有完整的产业链，充分的流动性，足以证明其是成熟、安全、稳定的商用金融系统。"

  [[Languages.cn.about.row]]

    [[Languages.cn.about.row.list]]
      icon = "fa-group"
      title = "社区"
      description =  '<p class="text-no-margin text-left text-muted">您可以在日益壮大的莱特币社区中寻求技术支持以及交流分享，例如： </p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">莱特币论坛</a></li> <li><a href="http://www.reddit.com/r/litecoin">莱特币Reddit社区</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">搜索推特上的用户</a></li> <li>加入<a href="http://freenode.net/" rel="nofollow">IRC 即时聊天网络</a>网络频道<a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#莱特币即时交流</a>(面向普通的交流用户)，<a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#莱特币-dev</a>(面向开发者交流)</li> </ul>'

    [[Languages.cn.about.row.list]]
      icon = "fa-laptop"
      title = "资源"
      description = '查看<a href="http://litecoin.info">莱特币维基百科</a>，可以获取莱特币的相关信息，以及查看所有支持莱特币的网站列表以及交易市场。 <br> 查看<a href="http://ltc.block-explorer.com/charts">莱特币交易图表</a>，获取最新的网上交易数据。 <br> 访问<a href="https://github.com/litecoin-project">GitHub.com/litecoin-project</a>，获取莱特币的源代码及相关项目。'

    [[Languages.cn.about.row.list]]
      icon = "fa-heart"
      title = "开源软件"
      description = "莱特币货币系统是一款遵循MIT/X11许协议的免费软件项目，它让您能够根据自己的需要对软件进行运行、修改和复制。如果你愿意，你也可以发行软件的修改版本。该软件以完全公开源码的形式发布，用户可以对二进制版本以及对应源代码进行独立验证。"

  [[Languages.cn.about.row]]
    [[Languages.cn.about.row.list]]
      icon = "fa-link"
      title = "数据块链"
      description = "莱特币数据块链与其竞争者——比特币相比起来，能够处理更大的交易量。由于数据块的产出更加频繁，该网络可以支持更多的交易，并且在将来无需修改软件。 <br />因此，商家可以获得更快的交易确认，而且在销售大额商品时依然能够等待更多的交易确认。"

    [[Languages.cn.about.row.list]]
      icon = "fa-lock"
      title = "钱包加密"
      description = "钱包加密能够保证您钱包中私钥的安全，从而让您可以查看交易情况及账户余额，但是在您使用莱特币之前必须输入密码。 <br />该功能不仅能够防止病毒及木马的侵扰，同时还是支付之前，一项合法性的有效检查。"

    [[Languages.cn.about.row.list]]
      icon = "fa-money"
      title = "挖矿奖励"
      description = "“矿工们”目前每数据块可以产出25个莱特币。每4年，生产的莱特币货币量将减少一半(每经过840000个数据块)。 <br />因此，莱特币网络生产的货币总量将是比特币的4倍，即8400万个莱特币。"

# download section
[Languages.cn.download]
  enable = true
  title = "下载"
  subtitle = "<a href='http://blog.litecoin.org/2015/12/litecoin-core-v01040.html'>Release Notes</a> | <a href='https://litecoin.info/Upgrading_Litecoin'>Upgrade Notes</a>"
  gpg = "GPG Signatures"
  download = "下载"
  source = "开源项目"
  walletfor = "Wallet for"
  releaseNotes = "#发行说明"
  upgradeNotes = "升级说明"


# Contact section
[Languages.cn.contact]
  enable = true
  # title = "Contact us"
  subtitle  = "您可以通过邮件 <a href='mailto:contact@litecoin.org'>contact@litecoin.org</a>联系莱特币的开发维护团队。"


# Footer section
[Languages.cn.footer]
  enable = true
  copyright = "Copyright &copy; 2011-2016 莱特币项目版权归开发者所有，并保留所有权利。"

  [[Languages.cn.footer.quicklinks]]
    text = "Privacy Policy"
    link = "#"

  [[Languages.cn.footer.quicklinks]]
    text = "Terms of Use"
    link = "#"
