# Site settings
baseurl = "https://stevesloan.github.io"
languageCode = "en-us"
title = "Litecoin - Open source P2P digital currency"
theme = "hugo-litecoin-theme"
googleAnalytics = ""
ignoreFiles = [ "\\.scss$", "\\.sass$" ]

# Link custom assets relative to /static
custom_css = []
custom_js  = []

# Possibility to disable external/additional fonts
# Exception: Fontawesome
disableFonts = false

[Taxonomies]
tag = "tags"

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[Languages]
[Languages.en]
weight = 1

# Hero section
[Languages.en.hero]
  # To change the background image of the hero, replace 'header-bg.jpg' in
  # the 'static/img' folder.
  title = "Global Decentralized Currency"
  subtitle = "Based on Blockchain Technology"
  button_text = "Download"

  # Navigation
  [Languages.en.navigation]
    brand = "litecoin"
    download = "Download"
    about = "About"
    team = "Team"
    contact = "Contact"

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://litecointalk.io/"
      name = "Forum"
      weight = 10


  # About section
  [Languages.en.about]
    enable = true
    title = "What is Litecoin?"
    subtitle = "Litecoin is a peer-to-peer Internet currency that enables instant, near-zero cost payments to anyone in the world. Litecoin is an open source, global payment network that is fully decentralized without any central authorities. Mathematics secures the network and empowers individuals to control their own finances. Litecoin features faster transaction confirmation times and improved storage efficiency than the leading math-based currency. With substantial industry support, trade volume and liquidity, Litecoin is a proven medium of commerce complementary to Bitcoin."

    [[Languages.en.about.row]]

      [[Languages.en.about.row.list]]
        icon = "fa-group"
        title = "Community"
        description = '<p class="text-no-margin text-left text-muted">Find support across a growing number of Litecoin communities:</p><ul class="text-muted text-left "> <li><a href="https://litecointalk.org">Litecoin Forums</a></li> <li><a href="http://www.reddit.com/r/litecoin">Reddit Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Search for Users on Twitter</a></li> <li><a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> network channels <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (for general users) and <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (for developers).</li> </ul>'

      [[Languages.en.about.row.list]]
        icon = "fa-laptop"
        title = "Resources"
        description = 'Find general information as well as a list of services and exchanges that support Litecoin at the <a href="http://litecoin.info">Litecoin Wiki</a>. <br> Up-to-date network statistics can be found at <a href="http://ltc.block-explorer.com/charts">Litecoin Block Explorer Charts</a>. <br> Source code for Litecoin Core and related projects are available on <a href="https://github.com/litecoin-project">GitHub</a>.'

      [[Languages.en.about.row.list]]
        icon = "fa-heart"
        title = "Open Source Software"
        description = "Litecoin is an open source software project released under the MIT/X11 license which gives you the power to run, modify, and copy the software and to distribute, at your option, modified copies of the software. The software is released in a transparent process that allows for independent verification of binaries and their corresponding source code."

      [[Languages.en.about.row.list]]
        icon = "fa-link"
        title = "Blockchain"
        description = "The Litecoin blockchain is capable of handling higher transaction volume than its counterpart - Bitcoin. Due to more frequent block generation, the network supports more transactions without a need to modify the software in the future. <br />As a result, merchants get faster confirmation times, while still having ability to wait for more confirmations when selling bigger ticket items."

      [[Languages.en.about.row.list]]
        icon = "fa-lock"
        title = "Wallet Encryption"
        description = "Wallet encryption allows you to secure your wallet, so that you can view transactions and your account balance, but are required to enter your password before spending litecoins. <br />This provides protection from wallet-stealing viruses and trojans as well as a sanity check before sending payments."

      [[Languages.en.about.row.list]]
        icon = "fa-money"
        title = "Mining Reward"
        description = "Miners are currently awarded with 25 new litecoins per block, an amount which gets halved roughly every 4 years (every 840,000 blocks). <br />The Litecoin network is therefore scheduled to produce 84 million litecoins, which is 4 times as many currency units as Bitcoin."

  # download section
  [Languages.en.download]
    enable = true
    title = "Download"
    subtitle = "<a href='http://blog.litecoin.org/2015/12/litecoin-core-v01040.html'>Release Notes</a> | <a href='https://litecoin.info/Upgrading_Litecoin'>Upgrade Notes</a>"


  # Contact section
  [Languages.en.contact]
    enable = true
    title = "Contact us"
    subtitle  = "You can contact Litecoin project development team at <a href='mailto:contact@litecoin.org'>contact@litecoin.org</a>"


  # Footer section
  [Languages.en.footer]
    enable = true
    copyright = "Copyright &copy; 2011-2016 Litecoin Project. <br />All rights reserved."

    [[Languages.en.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/LitecoinProject"

    [[Languages.en.footer.social]]
      icon = "fa-comments"
      link = "https://web.telegram.org/#/im?p=@Litecoin"

    [[Languages.en.footer.social]]
      icon = "fa-reddit-alien"
      link = "https://www.reddit.com/r/litecoin/"

    [[Languages.en.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[Languages.en.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"





[Languages.fr]
  weight = 2

  title = "Litecoin - Monnaie électronique décentralisée et open source"

[Languages.fr.hero]
  # To change the background image of the hero, replace 'header-bg.jpg' in
  # the 'static/img' folder.
  title = "fr-Global Decentralized Currency"
  subtitle = "frBased on Blockchain Technology"
  button_text = "fDownload"

[Languages.fr.Taxonomies]
plaque = "plaques"

[Languages.fr.navigation]
brand = "litecoin"
about = "About"

[Languages.fr.about]
title = "Litecoin, c'est quoi ?"
subtitle = "Litecoin est une devise Internet peer-to-peer, qui permet des paiements instantanés, avec des coûts proches de zéro à quiconque dans le monde. Litecoin est un réseau de paiement mondial open source, qui est entièrement décentralisé sans autorités centrale. Les utilisateurs peuvent mainteant contrôler leurs propres finances, securisées par un systeme basé entierement sur des mathématiques. Par rapport à Bitcoin, les transactions Litecoin sans plus rapides à confirmer et ont une efficacité de stockage accrue. De part son utilisation par l'industrie, le volume d'échange et de liquidité sur les marchés d'échange, Litecoin est un moyen de commerce complémentaire à Bitcoin, qui a fait ses preuves."

[[Languages.fr.about.row]]

[[Languages.fr.about.row.list]]
  icon = "fa-shopping-cart"
  title = "Community"
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

[[Languages.fr.about.row.list]]
  icon = "fa-laptop"
  title = "Resources"
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

[[Languages.fr.about.row.list]]
  icon = "fa-lock"
  title = "Wallet Encryption"
  description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."


[Languages.sp]
  weight = 2

  title = "Litecoin - sp"
